Fixing travis osx

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -277,7 +277,9 @@ matrix:
 
 script:
    - |
-     set -ex # Error out after first failure and print each command before executing   
+     # Error out after first failure and print each command before executing   
+     # not working for osx for unknown reasons
+     if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then set -ex ; fi
      
      export VISUS_INTERNAL_DEFAULT=${VISUS_INTERNAL_DEFAULT:-1}
      export PRETTY_LOG=${PRETTY_LOG:-1}
@@ -353,7 +355,8 @@ script:
         fi
      fi
      
-     set +ex # Stop printing each command     
+     # Stop printing each command 
+     if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then set +ex ; fi  
 
 before_deploy:
   - export SDIST_FILENAME=$(find ${TRAVIS_BUILD_DIR}/build/install/dist -iname "*.tar.gz")
