Fixing conda

diff --git a/.github/workflows/BuildOpenVisus.Conda.yml b/.github/workflows/BuildOpenVisus.Conda.yml
--- a/.github/workflows/BuildOpenVisus.Conda.yml
+++ b/.github/workflows/BuildOpenVisus.Conda.yml
@@ -157,7 +157,7 @@ jobs:
            cd build/Release/OpenVisus
            conda install anaconda-client conda-build 1>/dev/null || true #conda-build is needed for 'bdist_conda'
            rm -Rf $(find ${CONDA_PREFIX} -iname "openvisus*.tar.bz2")  || true
-           python setup.py -q bdist_conda 1>/dev/null
+           python setup.py -q bdist_conda 1>/dev/null || true # sometimes it fails to remove temporary directory
            CONDA_FILENAME=$(find ${CONDA_PREFIX} -iname "openvisus*.tar.bz2"  | head -n 1)       
            GIT_TAG=$(git describe --tags --exact-match 2>/dev/null || true)
            if [[ "${GIT_TAG}" != ""  ]] ; then
