working...

diff --git a/.github/workflows/build-openvisus.yml b/.github/workflows/build-openvisus.yml
--- a/.github/workflows/build-openvisus.yml
+++ b/.github/workflows/build-openvisus.yml
@@ -11,7 +11,7 @@ jobs:
         python-version: [ '3.6', '3.7', '3.8', '3.9'] 
     steps:
     
-    # ____________________________________________ CLONE OPENVISUS
+    # ____________________________________________ 
     - name: git clone OpenVisus
       uses: actions/checkout@v2
      
@@ -24,7 +24,7 @@ jobs:
         retry_wait_seconds: 5
         command: 'rm -Rf ExternalLibs/ospray_win && git clone https://github.com/sci-visus/ospray_win.git  ExternalLibs/ospray_win'
 
-    # ____________________________________________ INSTALL CMAKE
+    # ____________________________________________ 
     - name: Install CMake 
       uses: lukka/get-cmake@latest
       
@@ -88,16 +88,17 @@ jobs:
            
            cd  build/Release/OpenVisus
            
-           ${pythonLocation}/python setup.py -q bdist_wheel --python-tag=cp${PYTHON_VERSION:0:1}${PYTHON_VERSION:2:1} --plat-name=win_amd64
-           if [[ "${GIT_TAG}" != "" ]] ; then
-             ${pythonLocation}/python -m twine upload --username ${{ secrets.PYPI_USERNAME }} --password ${{ secrets.PYPI_PASSWORD }} --skip-existing  "dist/*.whl" 
-           fi
+           funtion DistribToPip() {
+             rm -Rf ./dist
+             ${pythonLocation}/python setup.py -q bdist_wheel --python-tag=cp${PYTHON_VERSION:0:1}${PYTHON_VERSION:2:1} --plat-name=win_amd64
+             if [[ "${GIT_TAG}" != "" ]] ; then
+               ${pythonLocation}/python -m twine upload --username ${{ secrets.PYPI_USERNAME }} --password ${{ secrets.PYPI_PASSWORD }} --skip-existing  "dist/*.whl" 
+             fi
+           }
            
+           DistribToPip
            rm -Rf QT_VERSION $(find . -iname "*VisusGui*")
-           ${pythonLocation}/python setup.py -q bdist_wheel --python-tag=cp${PYTHON_VERSION:0:1}${PYTHON_VERSION:2:1} --plat-name=win_amd64
-           if [[ "${GIT_TAG}" != "" ]] ; then
-             ${pythonLocation}/python -m twine upload --username ${{ secrets.PYPI_USERNAME }} --password ${{ secrets.PYPI_PASSWORD }} --skip-existing  "dist/*.whl" 
-           fi
+           DistribToPip
 
 
   # ///////////////////////////////////////////////////////////////////
@@ -131,14 +132,14 @@ jobs:
         retry_wait_seconds: 5
         command: 'cd /tmp && rm -Rf MacOSX-SDKs && git clone https://github.com/phracker/MacOSX-SDKs.git'
 
-    # ____________________________________________ INSTALL CPYTHON 
+    # ____________________________________________ 
     - name: Install CPython 
       uses: actions/setup-python@v2
       with:
         python-version: ${{ matrix.python-version }} 
         architecture: 'x64'
 
-    # ____________________________________________ INSTALL QT (use existing python see https://github.com/jurplel/install-qt-action)
+    # ____________________________________________ 
     - name: Install Qt
       uses: jurplel/install-qt-action@v2
       with:
@@ -186,17 +187,17 @@ jobs:
            
            cd build/Release/OpenVisus
            
-           ${pythonLocation}/python setup.py -q bdist_wheel --python-tag=cp${PYTHON_VERSION:0:1}${PYTHON_VERSION:2:1} --plat-name=macosx_10_9_x86_64 
-           if [[ "${GIT_TAG}" != "" ]] ; then
-             ${pythonLocation}/python -m twine upload --username ${{ secrets.PYPI_USERNAME }} --password ${{ secrets.PYPI_PASSWORD }} --skip-existing  "dist/*.whl" 
-           fi
+           function DistribToPip() {
+            rm -Rf ./dist
+             ${pythonLocation}/python setup.py -q bdist_wheel --python-tag=cp${PYTHON_VERSION:0:1}${PYTHON_VERSION:2:1} --plat-name=macosx_10_9_x86_64 
+             if [[ "${GIT_TAG}" != "" ]] ; then
+               ${pythonLocation}/python -m twine upload --username ${{ secrets.PYPI_USERNAME }} --password ${{ secrets.PYPI_PASSWORD }} --skip-existing  "dist/*.whl" 
+             fi           
+           }
            
-           # non-gui
+           DistribToPip
            rm -Rf QT_VERSION $(find . -iname "*VisusGui*")
-           ${pythonLocation}/python setup.py -q bdist_wheel --python-tag=cp${PYTHON_VERSION:0:1}${PYTHON_VERSION:2:1} --plat-name=macosx_10_9_x86_64 
-           if [[ "${GIT_TAG}" != "" ]] ; then
-             ${pythonLocation}/python -m twine upload --username ${{ secrets.PYPI_USERNAME }} --password ${{ secrets.PYPI_PASSWORD }} --skip-existing  "dist/*.whl" 
-           fi           
+           DistribToPip
 
   # ///////////////////////////////////////////////////////////////////
   cpython-ubuntu:
@@ -263,39 +264,41 @@ jobs:
            
            cd build/Release/OpenVisus
            
-           ${pythonLocation}/python setup.py -q bdist_wheel --python-tag=cp${PYTHON_VERSION:0:1}${PYTHON_VERSION:2:1} --plat-name=manylinux2010_x86_64
-           if [[ "${GIT_TAG}" != "" ]] ; then
-             ${pythonLocation}/python -m twine upload --username ${{ secrets.PYPI_USERNAME }} --password ${{ secrets.PYPI_PASSWORD }} --skip-existing  "dist/*.whl" 
-           fi
+           function DistribToPip() {
+            rm -Rf ./dist
+             ${pythonLocation}/python setup.py -q bdist_wheel --python-tag=cp${PYTHON_VERSION:0:1}${PYTHON_VERSION:2:1} --plat-name=manylinux2010_x86_64
+             if [[ "${GIT_TAG}" != "" ]] ; then
+               ${pythonLocation}/python -m twine upload --username ${{ secrets.PYPI_USERNAME }} --password ${{ secrets.PYPI_PASSWORD }} --skip-existing  "dist/*.whl" 
+             fi
+           }
            
-           # non-gui
+           DistribToPip
            rm -Rf QT_VERSION $(find . -iname "*VisusGui*")
-           ${pythonLocation}/python setup.py -q bdist_wheel --python-tag=cp${PYTHON_VERSION:0:1}${PYTHON_VERSION:2:1} --plat-name=manylinux2010_x86_64
-           if [[ "${GIT_TAG}" != "" ]] ; then
-             ${pythonLocation}/python -m twine upload --username ${{ secrets.PYPI_USERNAME }} --password ${{ secrets.PYPI_PASSWORD }} --skip-existing  "dist/*.whl" 
-           fi
+           DistribToPip
+           
+           
            
     # ____________________________________________ 
-    # for python version see Docker file (it's 3.7 on http:2.4 / debian:buster-slim
+    # for python version see Docker file (it's 3.9 now)
     - name: mod_visus
-      if: matrix.python-version=='3.7' 
+      if: matrix.python-version=='3.9' 
       shell: bash -l {0}
       run: |
            set -e
            set -x
-           
            GIT_TAG=$(git describe --tags --exact-match 2>/dev/null || true)
+           
+           echo ${{ secrets.DOCKER_TOKEN }} | docker login -u=${{ secrets.DOCKER_USERNAME }} --password-stdin
+           
            sleep 30 # give time pypi to get the pushed file
            
-           TAG=`${pythonLocation}/python Libs/swig/setup.py print-tag`
            cd Docker/mod_visus
-           echo ${{ secrets.DOCKER_TOKEN }} | docker login -u=${{ secrets.DOCKER_USERNAME }} --password-stdin
-           docker build --tag visus/mod_visus:$TAG --tag visus/mod_visus:latest --build-arg TAG=$TAG .
+           docker build --tag visus/mod_visus:$GIT_TAG --tag visus/mod_visus:latest --build-arg TAG=$GIT_TAG .
            if [[ "${GIT_TAG}" != "" ]] ; then
-             echo "Uploading  visus/mod_visus:$TAG to Docker"
-             docker push visus/mod_visus:$TAG
+             docker push visus/mod_visus:$GIT_TAG
              docker push visus/mod_visus:latest
            fi
+
 
   # ///////////////////////////////////////////////////////////////////
   conda-windows:
@@ -334,23 +337,13 @@ jobs:
     - name: Configure Miniconda 
       shell: bash -l {0}
       run: |
+           set -e
+           set -x
            conda config --set always_yes yes --set changeps1 no --set anaconda_upload no   1>/dev/null
            conda install conda                                                             1>/dev/null
-
-    # ____________________________________________ 
-    - name: Install Swig
-      shell: bash -l {0}
-      run: curl -L --insecure https://cfhcable.dl.sourceforge.net/project/swig/swigwin/swigwin-4.0.2/swigwin-4.0.2.zip -O  && unzip swigwin-4.0.2.zip # problems with choco
-
-    # ____________________________________________ 
-    - name: Install CMake
-      shell: bash -l {0}    
-      run: conda install -c conda-forge cmake
-
-    # ____________________________________________ 
-    - name: Install PyQt
-      shell: bash -l {0}
-      run: conda install -y pyqt=5.9  # -c conda-forge -y pyqt=5.12 (they rename DLLS, like Qt5Core.dll->Qt5Core_conda.dll))
+           curl -L --insecure https://cfhcable.dl.sourceforge.net/project/swig/swigwin/swigwin-4.0.2/swigwin-4.0.2.zip -O && unzip swigwin-4.0.2.zip # problems with choco
+           conda install -c conda-forge cmake
+           conda install -y pyqt=5.9  # -c conda-forge -y pyqt=5.12 (they rename DLLS, like Qt5Core.dll->Qt5Core_conda.dll))
 
     # ____________________________________________ 
     - name: Compile 
@@ -383,97 +376,28 @@ jobs:
       run: |
            set -e  
            set -x 
-           cd build/Release/OpenVisus
+           
            conda install --yes anaconda-client  1>/dev/null  || true
            conda install --yes conda-build      1>/dev/null  || true
            conda install --yes wheel            1>/dev/null  || true
-           rm -Rf $(find ${CONDA_PREFIX} -iname "openvisus*.tar.bz2")  || true
-           python setup.py -q bdist_conda 1>/dev/null
-           CONDA_FILENAME=$(find ${CONDA_PREFIX} -iname "openvisus*.tar.bz2"  | head -n 1)       
+           export PATH=$HOME/anaconda3/bin:$PATH
+           
            GIT_TAG=$(git describe --tags --exact-match 2>/dev/null || true)
-           if [[ "${GIT_TAG}" != ""  ]] ; then
-             export PATH=$HOME/anaconda3/bin:$PATH
-             anaconda --verbose --show-traceback  -t ${{ secrets.ANACONDA_TOKEN }}   upload "${CONDA_FILENAME}"
-           fi
-
-  # ///////////////////////////////////////////////////////////////////
-  conda-ubuntu:
-    runs-on: "ubuntu-latest"
-    strategy:
-      fail-fast: false
-      matrix:
-        python-version: [ '3.6', '3.7', '3.8', '3.9'] 
-    steps:
-    
-    # ____________________________________________ 
-    - name: git clone OpenVisus
-      uses: actions/checkout@v2    
-
-    # ____________________________________________ 
-    - name: Install Miniconda 
-      uses: conda-incubator/setup-miniconda@v2
-      continue-on-error: true # if fails the cleaning process
-      with:
-        miniconda-version: 'latest'
-        python-version: ${{ matrix.python-version }}
-        activate-environment: tmp
-        auto-update-conda: false
-        channels: conda-forge,defaults
-
-    # ____________________________________________ 
-    - name: Configure Miniconda 
-      shell: bash -l {0}
-      run: |
-           conda config --set always_yes yes --set changeps1 no --set anaconda_upload no   1>/dev/null
-           conda install conda                                                             1>/dev/null
-
-    # ____________________________________________
-    - name: Install CMake 
-      shell: bash -l {0}    
-      run: conda install -c conda-forge cmake
-
-    # ____________________________________________
-    - name: Compile  
-      shell: bash -l {0}
-      run: |
-           set -e
-           set -x
-           # i can use the pyqt one, but I would need to share the directory to docker, for simplicity I'm not doing it
-           docker run -e PYTHON_VERSION=${{ matrix.python-version }} -e Qt5_DIR=/opt/qt512 -v ${PWD}:${PWD}  -w ${PWD} visus/portable-linux-binaries /bin/bash -c "./scripts/build_linux.sh"
-           sudo chown -R root:root  build
-           sudo chmod -R a+rwx      build
-
-    # ____________________________________________ 
-    - name: Test  
-      shell: bash -l {0}
-      run: |
-           set -e
-           set -x
-           which python
+           
            cd build/Release/OpenVisus
-           export PYTHONPATH=../
-           python -m OpenVisus configure  || true  # segmentation fault problem on linux
-           python -m OpenVisus test
-           python -m OpenVisus test-gui
+           
+           function DistribToConda() {
+             rm -Rf $(find ${CONDA_PREFIX} -iname "openvisus*.tar.bz2")  || true
+             python setup.py -q bdist_conda 1>/dev/null
+             if [[ "${GIT_TAG}" != ""  ]] ; then
+               anaconda --verbose --show-traceback  -t ${{ secrets.ANACONDA_TOKEN }}   upload `find ${CONDA_PREFIX} -iname "openvisus*.tar.bz2"  | head -n 1`
+             fi
+           }
+           
+           DistribToConda
+           rm -Rf QT_VERSION $(find . -iname "*VisusGui*")
+           DistribToConda
 
-    # ____________________________________________ 
-    - name: Distrib 
-      shell: bash -l {0}   
-      run: |
-           set -e
-           set -x
-           cd build/Release/OpenVisus
-           conda install --yes anaconda-client  1>/dev/null  || true
-           conda install --yes conda-build      1>/dev/null  || true
-           conda install --yes wheel            1>/dev/null  || true
-           rm -Rf $(find ${CONDA_PREFIX} -iname "openvisus*.tar.bz2")  || true
-           python setup.py -q bdist_conda 1>/dev/null
-           CONDA_FILENAME=$(find ${CONDA_PREFIX} -iname "openvisus*.tar.bz2"  | head -n 1)       
-           GIT_TAG=$(git describe --tags --exact-match 2>/dev/null || true)
-           if [[ "${GIT_TAG}" != ""  ]] ; then
-             export PATH=$HOME/anaconda3/bin:$PATH
-             anaconda --verbose --show-traceback  -t ${{ secrets.ANACONDA_TOKEN }}   upload "${CONDA_FILENAME}"
-           fi
 
   # ///////////////////////////////////////////////////////////////////
   conda-macos:
@@ -512,24 +436,14 @@ jobs:
     - name: Configure Miniconda 
       shell: bash -l {0}
       run: |
+           set -e
+           set -x
            conda config --set always_yes yes --set changeps1 no --set anaconda_upload no   1>/dev/null
            conda install conda                                                             1>/dev/null
-
-    # ____________________________________________ 
-    - name: Install Swig 
-      shell: bash -l {0}
-      run: brew install swig
-      
-    # ____________________________________________ 
-    - name: Install CMake
-      shell: bash -l {0}    
-      run: brew install cmake # problems with conda
-      
-
-    # ____________________________________________ 
-    - name: Install PyQt 
-      shell: bash -l {0}
-      run: conda install -c conda-forge -y pyqt=5.12
+           
+           brew install swig
+           brew install cmake # problems with conda
+           conda install -c conda-forge -y pyqt=5.12
 
     # ____________________________________________ 
     - name: Compile 
@@ -562,15 +476,114 @@ jobs:
       run: |
            set -e
            set -x
-           cd build/Release/OpenVisus
+           
            conda install --yes anaconda-client  1>/dev/null  || true
            conda install --yes conda-build      1>/dev/null  || true
            conda install --yes wheel            1>/dev/null  || true
-           rm -Rf $(find ${CONDA_PREFIX} -iname "openvisus*.tar.bz2")  || true
-           python setup.py -q bdist_conda 1>/dev/null
-           CONDA_FILENAME=$(find ${CONDA_PREFIX} -iname "openvisus*.tar.bz2"  | head -n 1)
+           export PATH=$HOME/anaconda3/bin:$PATH
+           
            GIT_TAG=$(git describe --tags --exact-match 2>/dev/null || true)
-           if [[ "${GIT_TAG}" != ""  ]] ; then
-             export PATH=$HOME/anaconda3/bin:$PATH
-             anaconda --verbose --show-traceback  -t ${{ secrets.ANACONDA_TOKEN }}   upload "${CONDA_FILENAME}"
-           fi
+           
+           cd build/Release/OpenVisus
+           
+           function DistribToConda() {
+             rm -Rf $(find ${CONDA_PREFIX} -iname "openvisus*.tar.bz2")  || true
+             python setup.py -q bdist_conda 1>/dev/null
+             if [[ "${GIT_TAG}" != ""  ]] ; then
+               anaconda --verbose --show-traceback  -t ${{ secrets.ANACONDA_TOKEN }}   upload `find ${CONDA_PREFIX} -iname "openvisus*.tar.bz2"  | head -n 1`
+             fi
+           }
+           
+           DistribToConda
+           rm -Rf QT_VERSION $(find . -iname "*VisusGui*")
+           DistribToConda
+
+  # ///////////////////////////////////////////////////////////////////
+  conda-ubuntu:
+    runs-on: "ubuntu-latest"
+    strategy:
+      fail-fast: false
+      matrix:
+        python-version: [ '3.6', '3.7', '3.8', '3.9'] 
+    steps:
+    
+    # ____________________________________________ 
+    - name: git clone OpenVisus
+      uses: actions/checkout@v2    
+
+    # ____________________________________________ 
+    - name: Install Miniconda 
+      uses: conda-incubator/setup-miniconda@v2
+      continue-on-error: true # if fails the cleaning process
+      with:
+        miniconda-version: 'latest'
+        python-version: ${{ matrix.python-version }}
+        activate-environment: tmp
+        auto-update-conda: false
+        channels: conda-forge,defaults
+
+    # ____________________________________________ 
+    - name: Configure Miniconda 
+      shell: bash -l {0}
+      run: |
+           conda config --set always_yes yes --set changeps1 no --set anaconda_upload no   1>/dev/null
+           conda install conda                                                             1>/dev/null
+
+    # ____________________________________________
+    - name: Install CMake 
+      shell: bash -l {0}    
+      run: |
+           conda install -c conda-forge cmake
+
+    # ____________________________________________
+    - name: Compile  
+      shell: bash -l {0}
+      run: |
+           set -e
+           set -x
+           # i can use the pyqt one, but I would need to share the directory to docker, for simplicity I'm not doing it
+           docker run -e PYTHON_VERSION=${{ matrix.python-version }} -e Qt5_DIR=/opt/qt512 -v ${PWD}:${PWD}  -w ${PWD} visus/portable-linux-binaries /bin/bash -c "./scripts/build_linux.sh"
+           sudo chown -R root:root  build
+           sudo chmod -R a+rwx      build
+
+    # ____________________________________________ 
+    - name: Test
+      shell: bash -l {0}
+      run: |
+           set -e
+           set -x
+           which python
+           cd build/Release/OpenVisus
+           export PYTHONPATH=../
+           python -m OpenVisus configure  || true  # segmentation fault problem on linux
+           python -m OpenVisus test
+           python -m OpenVisus test-gui
+
+    # ____________________________________________ 
+    - name: Distrib 
+      shell: bash -l {0}
+      run: |
+           set -e
+           set -x
+           
+           conda install --yes anaconda-client  1>/dev/null  || true
+           conda install --yes conda-build      1>/dev/null  || true
+           conda install --yes wheel            1>/dev/null  || true
+           
+           export PATH=$HOME/anaconda3/bin:$PATH
+           
+           GIT_TAG=$(git describe --tags --exact-match 2>/dev/null || true)
+           
+           cd build/Release/OpenVisus
+           
+           function DistribToConda() {
+           rm -Rf $(find ${CONDA_PREFIX} -iname "openvisus*.tar.bz2")  || true
+             python setup.py -q bdist_conda 1>/dev/null
+             if [[ "${GIT_TAG}" != ""  ]] ; then
+               anaconda --verbose --show-traceback  -t ${{ secrets.ANACONDA_TOKEN }}   upload `find ${CONDA_PREFIX} -iname "openvisus*.tar.bz2"  | head -n 1`
+             fi
+           }
+           
+           DistribToConda
+           rm -Rf QT_VERSION $(find . -iname "*VisusGui*")
+           DistribToConda
