working..

diff --git a/.github/workflows/build-macos.yml b/.github/workflows/build-macos.yml
--- a/.github/workflows/build-macos.yml
+++ b/.github/workflows/build-macos.yml
@@ -2,7 +2,7 @@ name: build-macos
 on: [push]
 jobs:
 
-  Build:
+  build-on-cpython:
     runs-on: "macos-latest"
     strategy:
       fail-fast: false  
@@ -98,4 +98,107 @@ jobs:
            echo "GIT_TAG $GIT_TAG"
            if [[ "${GIT_TAG}" != "" ]] ; then
              ${pythonLocation}/python -m twine upload --username ${{ secrets.PYPI_USERNAME }} --password ${{ secrets.PYPI_PASSWORD }} --skip-existing  "dist/*.whl" 
+           fi
+
+  build-on-conda:
+    runs-on: "macos-latest"
+    strategy:
+      fail-fast: false  
+      matrix:
+        python-version: [ '3.6', '3.7', '3.8', '3.9'] 
+    steps:
+    
+    - name: git clone OpenVisus
+      uses: actions/checkout@v2 
+      
+    - name: filter CI
+      uses: mstachniuk/ci-skip@v1
+      with:
+        fail-fast: true
+        exit-code: 0
+        commit-filter: '[no-ci];[windows];[linux];[cpython]'
+        commit-filter-separator: ';'
+
+    - name: Install SDK 10.9
+      uses: nick-invision/retry@v1
+      with:
+        max_attempts: 3
+        timeout_minutes: 5
+        retry_wait_seconds: 5
+        command: 'cd /tmp && rm -Rf MacOSX-SDKs && git clone https://github.com/phracker/MacOSX-SDKs.git'
+
+    - name: Install Miniconda 
+      uses: conda-incubator/setup-miniconda@v2
+      continue-on-error: true # if fails the cleaning process
+      with:
+        miniconda-version: 'latest'
+        python-version: ${{ matrix.python-version }}
+        activate-environment: tmp
+        auto-update-conda: false
+        channels: conda-forge,defaults
+
+    - name: Configure Miniconda 
+      shell: bash -l {0}
+      run: |
+           conda config --set always_yes yes --set changeps1 no --set anaconda_upload no   1>/dev/null
+           conda install conda 1>/dev/null
+
+
+    - name: Install Swig
+      shell: bash -l {0}
+      run: brew install swig
+      
+    - name: Install CMake
+      shell: bash -l {0}    
+      run: brew install cmake # problems with conda installation
+      
+    - name: Install PyQt for osx
+      shell: bash -l {0}
+      run: conda install -c conda-forge -y pyqt=5.12
+    
+    - name: Compile
+      shell: bash -l {0}
+      run: |
+           set -e
+           set -x      
+           mkdir -p build
+           cd build
+           cmake \
+              -GXcode -DQt5_DIR="${CONDA_PREFIX}/lib/cmake/Qt5" \
+              -DCMAKE_OSX_SYSROOT="/tmp/MacOSX-SDKs/MacOSX10.9.sdk"  \
+              -DPython_EXECUTABLE=$(which python) \
+              -DVISUS_SLAM=1  \
+              ../
+           cmake --build ./ --target ALL_BUILD --config Release --parallel 4 
+           cmake --build ./ --target install   --config Release 
+
+    - name: Test  
+      shell: bash -l {0}
+      run: |
+           set -e
+           set -x
+           which python
+           cd build/Release/OpenVisus
+           export PYTHONPATH=../
+           python -m OpenVisus configure  || true  # segmentation fault problem on linux
+           python -m OpenVisus test
+           python -m OpenVisus test-gui
+
+    - name: Conda distribution
+      shell: bash -l {0}   
+      run: |
+           set -e
+           set -x
+           cd build/Release/OpenVisus
+           conda install --yes anaconda-client  1>/dev/null  || true
+           conda install --yes conda-build      1>/dev/null  || true
+           conda install --yes wheel            1>/dev/null  || true
+           rm -Rf $(find ${CONDA_PREFIX} -iname "openvisus*.tar.bz2")  || true
+           python setup.py -q bdist_conda 1>/dev/null
+           CONDA_FILENAME=$(find ${CONDA_PREFIX} -iname "openvisus*.tar.bz2"  | head -n 1)       
+           GIT_TAG=$(git describe --tags --exact-match 2>/dev/null || true)
+           echo "GIT_TAG=$GIT_TAG"
+           if [[ "${GIT_TAG}" != ""  ]] ; then
+             export PATH=$HOME/anaconda3/bin:$PATH
+             anaconda --verbose --show-traceback  -t ${{ secrets.ANACONDA_TOKEN }}   upload "${CONDA_FILENAME}"
            fi
